foldersTree = gFld("<b>audiere</b>", "", "")
     insDoc(foldersTree, gLnk("Audiere", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("audiere.cpp", "", "audiere_8cpp.html"))
       insDoc(aux1, gLnk("audiere.h", "", "audiere_8h.html"))
       insDoc(aux1, gLnk("config.h", "", "config_8h.html"))
       insDoc(aux1, gLnk("context.cpp", "", "context_8cpp.html"))
       insDoc(aux1, gLnk("context.hpp", "", "context_8hpp.html"))
       insDoc(aux1, gLnk("debug.cpp", "", "debug_8cpp.html"))
       insDoc(aux1, gLnk("debug.hpp", "", "debug_8hpp.html"))
       insDoc(aux1, gLnk("default_file.hpp", "", "default__file_8hpp.html"))
       insDoc(aux1, gLnk("endian.hpp", "", "endian_8hpp.html"))
       insDoc(aux1, gLnk("file.cpp", "", "file_8cpp.html"))
       insDoc(aux1, gLnk("file.hpp", "", "file_8hpp.html"))
       insDoc(aux1, gLnk("file_ansi.cpp", "", "file__ansi_8cpp.html"))
       insDoc(aux1, gLnk("file_win32.cpp", "", "file__win32_8cpp.html"))
       insDoc(aux1, gLnk("input.cpp", "", "input_8cpp.html"))
       insDoc(aux1, gLnk("input.hpp", "", "input_8hpp.html"))
       insDoc(aux1, gLnk("input_mod.cpp", "", "input__mod_8cpp.html"))
       insDoc(aux1, gLnk("input_mod.hpp", "", "input__mod_8hpp.html"))
       insDoc(aux1, gLnk("input_ogg.cpp", "", "input__ogg_8cpp.html"))
       insDoc(aux1, gLnk("input_ogg.hpp", "", "input__ogg_8hpp.html"))
       insDoc(aux1, gLnk("input_wav.cpp", "", "input__wav_8cpp.html"))
       insDoc(aux1, gLnk("input_wav.hpp", "", "input__wav_8hpp.html"))
       insDoc(aux1, gLnk("mainpage.doxy", "", "mainpage_8doxy.html"))
       insDoc(aux1, gLnk("mixer.cpp", "", "mixer_8cpp.html"))
       insDoc(aux1, gLnk("mixer.hpp", "", "mixer_8hpp.html"))
       insDoc(aux1, gLnk("output.cpp", "", "output_8cpp.html"))
       insDoc(aux1, gLnk("output.hpp", "", "output_8hpp.html"))
       insDoc(aux1, gLnk("output_al.cpp", "", "output__al_8cpp.html"))
       insDoc(aux1, gLnk("output_al.hpp", "", "output__al_8hpp.html"))
       insDoc(aux1, gLnk("output_ds.cpp", "", "output__ds_8cpp.html"))
       insDoc(aux1, gLnk("output_ds.hpp", "", "output__ds_8hpp.html"))
       insDoc(aux1, gLnk("output_ds3.cpp", "", "output__ds3_8cpp.html"))
       insDoc(aux1, gLnk("output_ds3.hpp", "", "output__ds3_8hpp.html"))
       insDoc(aux1, gLnk("output_ds8.hpp", "", "output__ds8_8hpp.html"))
       insDoc(aux1, gLnk("output_null.cpp", "", "output__null_8cpp.html"))
       insDoc(aux1, gLnk("output_null.hpp", "", "output__null_8hpp.html"))
       insDoc(aux1, gLnk("output_oss.cpp", "", "output__oss_8cpp.html"))
       insDoc(aux1, gLnk("output_oss.hpp", "", "output__oss_8hpp.html"))
       insDoc(aux1, gLnk("repeatable.cpp", "", "repeatable_8cpp.html"))
       insDoc(aux1, gLnk("repeatable.hpp", "", "repeatable_8hpp.html"))
       insDoc(aux1, gLnk("resampler.cpp", "", "resampler_8cpp.html"))
       insDoc(aux1, gLnk("resampler.hpp", "", "resampler_8hpp.html"))
       insDoc(aux1, gLnk("stream.cpp", "", "stream_8cpp.html"))
       insDoc(aux1, gLnk("stream.hpp", "", "stream_8hpp.html"))
       insDoc(aux1, gLnk("threads.hpp", "", "threads_8hpp.html"))
       insDoc(aux1, gLnk("threads_posix.cpp", "", "threads__posix_8cpp.html"))
       insDoc(aux1, gLnk("threads_win32.cpp", "", "threads__win32_8cpp.html"))
       insDoc(aux1, gLnk("timer.hpp", "", "timer_8hpp.html"))
       insDoc(aux1, gLnk("timer_ansi.cpp", "", "timer__ansi_8cpp.html"))
       insDoc(aux1, gLnk("timer_posix.cpp", "", "timer__posix_8cpp.html"))
       insDoc(aux1, gLnk("timer_win32.cpp", "", "timer__win32_8cpp.html"))
       insDoc(aux1, gLnk("utility.cpp", "", "utility_8cpp.html"))
       insDoc(aux1, gLnk("utility.hpp", "", "utility_8hpp.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("ADR_CONTEXT_ATTRimp", "", "structADR__CONTEXT__ATTRimp.html"))
       insDoc(aux1, gLnk("ADR_FileHandle", "", "structADR__FileHandle.html"))
       insDoc(aux1, gLnk("ADRFile", "", "classADRFile.html"))
       insDoc(aux1, gLnk("ADRFileSystem", "", "classADRFileSystem.html"))
       insDoc(aux1, gLnk("AI_CriticalSectionStruct", "", "structAI__CriticalSectionStruct.html"))
       insDoc(aux1, gLnk("AI_Lock", "", "classAI__Lock.html"))
       insDoc(aux1, gLnk("ALOutputContext", "", "classALOutputContext.html"))
       insDoc(aux1, gLnk("ALOutputStream", "", "classALOutputStream.html"))
       insDoc(aux1, gLnk("Context", "", "classContext.html"))
       insDoc(aux1, gLnk("DS3OutputContext", "", "classDS3OutputContext.html"))
       insDoc(aux1, gLnk("DS8OutputContext", "", "classDS8OutputContext.html"))
       insDoc(aux1, gLnk("DSOutputContext", "", "classDSOutputContext.html"))
       insDoc(aux1, gLnk("DSOutputStream", "", "classDSOutputStream.html"))
       insDoc(aux1, gLnk("IFile", "", "classIFile.html"))
       insDoc(aux1, gLnk("IFileSystem", "", "classIFileSystem.html"))
       insDoc(aux1, gLnk("IOutputContext", "", "classIOutputContext.html"))
       insDoc(aux1, gLnk("IOutputStream", "", "classIOutputStream.html"))
       insDoc(aux1, gLnk("ISampleSource", "", "classISampleSource.html"))
       insDoc(aux1, gLnk("Mixer", "", "classMixer.html"))
       insDoc(aux1, gLnk("MODInputStream", "", "classMODInputStream.html"))
       insDoc(aux1, gLnk("NullOutputContext", "", "classNullOutputContext.html"))
       insDoc(aux1, gLnk("NullOutputStream", "", "classNullOutputStream.html"))
       insDoc(aux1, gLnk("OGG_INTERNAL", "", "structOGG__INTERNAL.html"))
       insDoc(aux1, gLnk("OGGInputStream", "", "classOGGInputStream.html"))
       insDoc(aux1, gLnk("OSSOutputContext", "", "classOSSOutputContext.html"))
       insDoc(aux1, gLnk("OSSOutputStream", "", "classOSSOutputStream.html"))
       insDoc(aux1, gLnk("RepeatableStream", "", "classRepeatableStream.html"))
       insDoc(aux1, gLnk("Resampler", "", "classResampler.html"))
       insDoc(aux1, gLnk("Stream", "", "classStream.html"))
       insDoc(aux1, gLnk("Synchronized", "", "classSynchronized.html"))
       insDoc(aux1, gLnk("ThreadInternal", "", "structThreadInternal.html"))
       insDoc(aux1, gLnk("WAVInputStream", "", "classWAVInputStream.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("ADR_CONTEXT_ATTRimp", "", "structADR__CONTEXT__ATTRimp.html"))
       insDoc(aux1, gLnk("ADR_FileHandle", "", "structADR__FileHandle.html"))
       insDoc(aux1, gLnk("AI_CriticalSectionStruct", "", "structAI__CriticalSectionStruct.html"))
       insDoc(aux1, gLnk("AI_Lock", "", "classAI__Lock.html"))
  aux2 = insFld(aux1, gFld("IFile", "", "classIFile.html"))
         insDoc(aux2, gLnk("ADRFile", "", "classADRFile.html"))
  aux2 = insFld(aux1, gFld("IFileSystem", "", "classIFileSystem.html"))
         insDoc(aux2, gLnk("ADRFileSystem", "", "classADRFileSystem.html"))
  aux2 = insFld(aux1, gFld("IOutputContext", "", "classIOutputContext.html"))
         insDoc(aux2, gLnk("ALOutputContext", "", "classALOutputContext.html"))
    aux3 = insFld(aux2, gFld("DSOutputContext", "", "classDSOutputContext.html"))
           insDoc(aux3, gLnk("DS3OutputContext", "", "classDS3OutputContext.html"))
           insDoc(aux3, gLnk("DS8OutputContext", "", "classDS8OutputContext.html"))
         insDoc(aux2, gLnk("NullOutputContext", "", "classNullOutputContext.html"))
         insDoc(aux2, gLnk("OSSOutputContext", "", "classOSSOutputContext.html"))
  aux2 = insFld(aux1, gFld("IOutputStream", "", "classIOutputStream.html"))
         insDoc(aux2, gLnk("ALOutputStream", "", "classALOutputStream.html"))
         insDoc(aux2, gLnk("DSOutputStream", "", "classDSOutputStream.html"))
         insDoc(aux2, gLnk("NullOutputStream", "", "classNullOutputStream.html"))
         insDoc(aux2, gLnk("OSSOutputStream", "", "classOSSOutputStream.html"))
  aux2 = insFld(aux1, gFld("ISampleSource", "", "classISampleSource.html"))
         insDoc(aux2, gLnk("Mixer", "", "classMixer.html"))
         insDoc(aux2, gLnk("MODInputStream", "", "classMODInputStream.html"))
         insDoc(aux2, gLnk("OGGInputStream", "", "classOGGInputStream.html"))
         insDoc(aux2, gLnk("RepeatableStream", "", "classRepeatableStream.html"))
         insDoc(aux2, gLnk("Resampler", "", "classResampler.html"))
         insDoc(aux2, gLnk("WAVInputStream", "", "classWAVInputStream.html"))
       insDoc(aux1, gLnk("OGG_INTERNAL", "", "structOGG__INTERNAL.html"))
       insDoc(aux1, gLnk("Stream", "", "classStream.html"))
  aux2 = insFld(aux1, gFld("Synchronized", "", "classSynchronized.html"))
         insDoc(aux2, gLnk("Context", "", "classContext.html"))
       insDoc(aux1, gLnk("ThreadInternal", "", "structThreadInternal.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Graphical Class Hierarchy", "", "inherits.html"))
