foldersTree = gFld("<b>audiere</b>", "", "")
     insDoc(foldersTree, gLnk("Audiere 1.9.1", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("audiere.h", "", "audiere_8h.html"))
       insDoc(aux1, gLnk("debug.cpp", "", "debug_8cpp.html"))
       insDoc(aux1, gLnk("debug.h", "", "debug_8h.html"))
       insDoc(aux1, gLnk("default_file.h", "", "default__file_8h.html"))
       insDoc(aux1, gLnk("device.cpp", "", "device_8cpp.html"))
       insDoc(aux1, gLnk("device_al.cpp", "", "device__al_8cpp.html"))
       insDoc(aux1, gLnk("device_al.h", "", "device__al_8h.html"))
       insDoc(aux1, gLnk("device_ds.cpp", "", "device__ds_8cpp.html"))
       insDoc(aux1, gLnk("device_ds.h", "", "device__ds_8h.html"))
       insDoc(aux1, gLnk("device_ds_buffer.cpp", "", "device__ds__buffer_8cpp.html"))
       insDoc(aux1, gLnk("device_ds_buffer.h", "", "device__ds__buffer_8h.html"))
       insDoc(aux1, gLnk("device_ds_stream.cpp", "", "device__ds__stream_8cpp.html"))
       insDoc(aux1, gLnk("device_ds_stream.h", "", "device__ds__stream_8h.html"))
       insDoc(aux1, gLnk("device_mixer.cpp", "", "device__mixer_8cpp.html"))
       insDoc(aux1, gLnk("device_mixer.h", "", "device__mixer_8h.html"))
       insDoc(aux1, gLnk("device_mm.cpp", "", "device__mm_8cpp.html"))
       insDoc(aux1, gLnk("device_mm.h", "", "device__mm_8h.html"))
       insDoc(aux1, gLnk("device_null.cpp", "", "device__null_8cpp.html"))
       insDoc(aux1, gLnk("device_null.h", "", "device__null_8h.html"))
       insDoc(aux1, gLnk("device_oal.cpp", "", "device__oal_8cpp.html"))
       insDoc(aux1, gLnk("device_oal.h", "", "device__oal_8h.html"))
       insDoc(aux1, gLnk("device_oss.cpp", "", "device__oss_8cpp.html"))
       insDoc(aux1, gLnk("device_oss.h", "", "device__oss_8h.html"))
       insDoc(aux1, gLnk("file_ansi.cpp", "", "file__ansi_8cpp.html"))
       insDoc(aux1, gLnk("input.cpp", "", "input_8cpp.html"))
       insDoc(aux1, gLnk("input_flac.cpp", "", "input__flac_8cpp.html"))
       insDoc(aux1, gLnk("input_flac.h", "", "input__flac_8h.html"))
       insDoc(aux1, gLnk("input_mod.cpp", "", "input__mod_8cpp.html"))
       insDoc(aux1, gLnk("input_mod.h", "", "input__mod_8h.html"))
       insDoc(aux1, gLnk("input_mp3.cpp", "", "input__mp3_8cpp.html"))
       insDoc(aux1, gLnk("input_mp3.h", "", "input__mp3_8h.html"))
       insDoc(aux1, gLnk("input_ogg.cpp", "", "input__ogg_8cpp.html"))
       insDoc(aux1, gLnk("input_ogg.h", "", "input__ogg_8h.html"))
       insDoc(aux1, gLnk("input_wav.cpp", "", "input__wav_8cpp.html"))
       insDoc(aux1, gLnk("input_wav.h", "", "input__wav_8h.html"))
       insDoc(aux1, gLnk("internal.h", "", "internal_8h.html"))
       insDoc(aux1, gLnk("mainpage.doxy", "", "mainpage_8doxy.html"))
       insDoc(aux1, gLnk("noise.cpp", "", "noise_8cpp.html"))
       insDoc(aux1, gLnk("repeatable.cpp", "", "repeatable_8cpp.html"))
       insDoc(aux1, gLnk("repeatable.h", "", "repeatable_8h.html"))
       insDoc(aux1, gLnk("resampler.cpp", "", "resampler_8cpp.html"))
       insDoc(aux1, gLnk("resampler.h", "", "resampler_8h.html"))
       insDoc(aux1, gLnk("sample_buffer.cpp", "", "sample__buffer_8cpp.html"))
       insDoc(aux1, gLnk("sound.cpp", "", "sound_8cpp.html"))
       insDoc(aux1, gLnk("sound_effect.cpp", "", "sound__effect_8cpp.html"))
       insDoc(aux1, gLnk("square_wave.cpp", "", "square__wave_8cpp.html"))
       insDoc(aux1, gLnk("threads.h", "", "threads_8h.html"))
       insDoc(aux1, gLnk("threads_posix.cpp", "", "threads__posix_8cpp.html"))
       insDoc(aux1, gLnk("threads_win32.cpp", "", "threads__win32_8cpp.html"))
       insDoc(aux1, gLnk("timer.h", "", "timer_8h.html"))
       insDoc(aux1, gLnk("timer_ansi.cpp", "", "timer__ansi_8cpp.html"))
       insDoc(aux1, gLnk("timer_posix.cpp", "", "timer__posix_8cpp.html"))
       insDoc(aux1, gLnk("timer_win32.cpp", "", "timer__win32_8cpp.html"))
       insDoc(aux1, gLnk("tone.cpp", "", "tone_8cpp.html"))
       insDoc(aux1, gLnk("types.h", "", "types_8h.html"))
       insDoc(aux1, gLnk("utility.cpp", "", "utility_8cpp.html"))
       insDoc(aux1, gLnk("utility.h", "", "utility_8h.html"))
       insDoc(aux1, gLnk("version.cpp", "", "version_8cpp.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("audiere::AI_CriticalSectionStruct", "", "structaudiere_1_1AI__CriticalSectionStruct.html"))
       insDoc(aux1, gLnk("audiere::ALAudioDevice", "", "classaudiere_1_1ALAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::AudioDevice", "", "classaudiere_1_1AudioDevice.html"))
       insDoc(aux1, gLnk("audiere::BufferStream", "", "classaudiere_1_1BufferStream.html"))
       insDoc(aux1, gLnk("audiere::CFile", "", "classaudiere_1_1CFile.html"))
       insDoc(aux1, gLnk("audiere::DSAudioDevice", "", "classaudiere_1_1DSAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::DSOutputBuffer", "", "classaudiere_1_1DSOutputBuffer.html"))
       insDoc(aux1, gLnk("audiere::DSOutputStream", "", "classaudiere_1_1DSOutputStream.html"))
       insDoc(aux1, gLnk("audiere::File", "", "classaudiere_1_1File.html"))
       insDoc(aux1, gLnk("audiere::FileFormatDesc", "", "structaudiere_1_1FileFormatDesc.html"))
       insDoc(aux1, gLnk("audiere::FLACInputStream", "", "classaudiere_1_1FLACInputStream.html"))
       insDoc(aux1, gLnk("audiere::Guard", "", "classaudiere_1_1Guard.html"))
       insDoc(aux1, gLnk("audiere::Lock", "", "classaudiere_1_1Lock.html"))
       insDoc(aux1, gLnk("audiere::Log", "", "classaudiere_1_1Log.html"))
       insDoc(aux1, gLnk("audiere::MixerDevice", "", "classaudiere_1_1MixerDevice.html"))
       insDoc(aux1, gLnk("audiere::MixerStream", "", "classaudiere_1_1MixerStream.html"))
       insDoc(aux1, gLnk("audiere::MMAudioDevice", "", "classaudiere_1_1MMAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::MODInputStream", "", "classaudiere_1_1MODInputStream.html"))
       insDoc(aux1, gLnk("audiere::MP3InputStream", "", "classaudiere_1_1MP3InputStream.html"))
       insDoc(aux1, gLnk("audiere::MultipleSoundEffect", "", "classaudiere_1_1MultipleSoundEffect.html"))
       insDoc(aux1, gLnk("audiere::MyFLACDecoder", "", "classaudiere_1_1MyFLACDecoder.html"))
       insDoc(aux1, gLnk("audiere::MyLoader", "", "classaudiere_1_1MyLoader.html"))
       insDoc(aux1, gLnk("audiere::NullAudioDevice", "", "classaudiere_1_1NullAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::NullOutputStream", "", "classaudiere_1_1NullOutputStream.html"))
       insDoc(aux1, gLnk("audiere::OALAudioDevice", "", "classaudiere_1_1OALAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::OALOutputStream", "", "classaudiere_1_1OALOutputStream.html"))
       insDoc(aux1, gLnk("audiere::OGGInputStream", "", "classaudiere_1_1OGGInputStream.html"))
       insDoc(aux1, gLnk("audiere::OSSAudioDevice", "", "classaudiere_1_1OSSAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::OutputStream", "", "classaudiere_1_1OutputStream.html"))
       insDoc(aux1, gLnk("audiere::ParameterList", "", "classaudiere_1_1ParameterList.html"))
       insDoc(aux1, gLnk("audiere::PinkNoise", "", "classaudiere_1_1PinkNoise.html"))
       insDoc(aux1, gLnk("audiere::QueueBuffer", "", "classaudiere_1_1QueueBuffer.html"))
       insDoc(aux1, gLnk("audiere::RefCounted", "", "classaudiere_1_1RefCounted.html"))
       insDoc(aux1, gLnk("audiere::RefImplementation< Interface >", "", "classaudiere_1_1RefImplementation.html"))
       insDoc(aux1, gLnk("audiere::RefPtr< T >", "", "classaudiere_1_1RefPtr.html"))
       insDoc(aux1, gLnk("audiere::RepeatableStream", "", "classaudiere_1_1RepeatableStream.html"))
       insDoc(aux1, gLnk("audiere::Resampler", "", "classaudiere_1_1Resampler.html"))
       insDoc(aux1, gLnk("audiere::SampleBuffer", "", "classaudiere_1_1SampleBuffer.html"))
       insDoc(aux1, gLnk("audiere::SampleBufferImpl", "", "classaudiere_1_1SampleBufferImpl.html"))
       insDoc(aux1, gLnk("audiere::SampleSource", "", "classaudiere_1_1SampleSource.html"))
       insDoc(aux1, gLnk("audiere::SineWave", "", "classaudiere_1_1SineWave.html"))
       insDoc(aux1, gLnk("audiere::SingleSoundEffect", "", "classaudiere_1_1SingleSoundEffect.html"))
       insDoc(aux1, gLnk("audiere::SizedBuffer", "", "classaudiere_1_1SizedBuffer.html"))
       insDoc(aux1, gLnk("audiere::SoundEffect", "", "classaudiere_1_1SoundEffect.html"))
       insDoc(aux1, gLnk("audiere::SquareWave", "", "classaudiere_1_1SquareWave.html"))
       insDoc(aux1, gLnk("audiere::Synchronized", "", "classaudiere_1_1Synchronized.html"))
       insDoc(aux1, gLnk("audiere::ThreadedDevice", "", "classaudiere_1_1ThreadedDevice.html"))
       insDoc(aux1, gLnk("audiere::ThreadInternal", "", "structaudiere_1_1ThreadInternal.html"))
       insDoc(aux1, gLnk("audiere::UnseekableSource", "", "classaudiere_1_1UnseekableSource.html"))
       insDoc(aux1, gLnk("audiere::WAVInputStream", "", "classaudiere_1_1WAVInputStream.html"))
       insDoc(aux1, gLnk("audiere::WhiteNoise", "", "classaudiere_1_1WhiteNoise.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("audiere::AI_CriticalSectionStruct", "", "structaudiere_1_1AI__CriticalSectionStruct.html"))
       insDoc(aux1, gLnk("audiere::FileFormatDesc", "", "structaudiere_1_1FileFormatDesc.html"))
       insDoc(aux1, gLnk("audiere::Guard", "", "classaudiere_1_1Guard.html"))
       insDoc(aux1, gLnk("audiere::Lock", "", "classaudiere_1_1Lock.html"))
       insDoc(aux1, gLnk("audiere::Log", "", "classaudiere_1_1Log.html"))
       insDoc(aux1, gLnk("audiere::MyFLACDecoder", "", "classaudiere_1_1MyFLACDecoder.html"))
       insDoc(aux1, gLnk("audiere::MyLoader", "", "classaudiere_1_1MyLoader.html"))
       insDoc(aux1, gLnk("audiere::ParameterList", "", "classaudiere_1_1ParameterList.html"))
       insDoc(aux1, gLnk("audiere::QueueBuffer", "", "classaudiere_1_1QueueBuffer.html"))
  aux2 = insFld(aux1, gFld("audiere::RefCounted", "", "classaudiere_1_1RefCounted.html"))
    aux3 = insFld(aux2, gFld("audiere::AudioDevice", "", "classaudiere_1_1AudioDevice.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< AudioDevice >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::DSAudioDevice", "", "classaudiere_1_1DSAudioDevice.html"))
        aux5 = insFld(aux4, gFld("audiere::MixerDevice", "", "classaudiere_1_1MixerDevice.html"))
               insDoc(aux5, gLnk("audiere::ALAudioDevice", "", "classaudiere_1_1ALAudioDevice.html"))
               insDoc(aux5, gLnk("audiere::MMAudioDevice", "", "classaudiere_1_1MMAudioDevice.html"))
               insDoc(aux5, gLnk("audiere::OSSAudioDevice", "", "classaudiere_1_1OSSAudioDevice.html"))
             insDoc(aux4, gLnk("audiere::NullAudioDevice", "", "classaudiere_1_1NullAudioDevice.html"))
             insDoc(aux4, gLnk("audiere::OALAudioDevice", "", "classaudiere_1_1OALAudioDevice.html"))
             insDoc(aux4, gLnk("audiere::ThreadedDevice", "", "classaudiere_1_1ThreadedDevice.html"))
    aux3 = insFld(aux2, gFld("audiere::File", "", "classaudiere_1_1File.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< File >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::CFile", "", "classaudiere_1_1CFile.html"))
    aux3 = insFld(aux2, gFld("audiere::OutputStream", "", "classaudiere_1_1OutputStream.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< OutputStream >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::DSOutputBuffer", "", "classaudiere_1_1DSOutputBuffer.html"))
             insDoc(aux4, gLnk("audiere::DSOutputStream", "", "classaudiere_1_1DSOutputStream.html"))
             insDoc(aux4, gLnk("audiere::MixerStream", "", "classaudiere_1_1MixerStream.html"))
             insDoc(aux4, gLnk("audiere::NullOutputStream", "", "classaudiere_1_1NullOutputStream.html"))
             insDoc(aux4, gLnk("audiere::OALOutputStream", "", "classaudiere_1_1OALOutputStream.html"))
    aux3 = insFld(aux2, gFld("audiere::SampleBuffer", "", "classaudiere_1_1SampleBuffer.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< SampleBuffer >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::SampleBufferImpl", "", "classaudiere_1_1SampleBufferImpl.html"))
    aux3 = insFld(aux2, gFld("audiere::SampleSource", "", "classaudiere_1_1SampleSource.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< audiere::SampleSource >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::FLACInputStream", "", "classaudiere_1_1FLACInputStream.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< SampleSource >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::BufferStream", "", "classaudiere_1_1BufferStream.html"))
             insDoc(aux4, gLnk("audiere::OGGInputStream", "", "classaudiere_1_1OGGInputStream.html"))
             insDoc(aux4, gLnk("audiere::RepeatableStream", "", "classaudiere_1_1RepeatableStream.html"))
             insDoc(aux4, gLnk("audiere::Resampler", "", "classaudiere_1_1Resampler.html"))
        aux5 = insFld(aux4, gFld("audiere::UnseekableSource", "", "classaudiere_1_1UnseekableSource.html"))
               insDoc(aux5, gLnk("audiere::MODInputStream", "", "classaudiere_1_1MODInputStream.html"))
               insDoc(aux5, gLnk("audiere::MP3InputStream", "", "classaudiere_1_1MP3InputStream.html"))
               insDoc(aux5, gLnk("audiere::PinkNoise", "", "classaudiere_1_1PinkNoise.html"))
               insDoc(aux5, gLnk("audiere::SineWave", "", "classaudiere_1_1SineWave.html"))
               insDoc(aux5, gLnk("audiere::SquareWave", "", "classaudiere_1_1SquareWave.html"))
               insDoc(aux5, gLnk("audiere::WhiteNoise", "", "classaudiere_1_1WhiteNoise.html"))
             insDoc(aux4, gLnk("audiere::WAVInputStream", "", "classaudiere_1_1WAVInputStream.html"))
    aux3 = insFld(aux2, gFld("audiere::SoundEffect", "", "classaudiere_1_1SoundEffect.html"))
      aux4 = insFld(aux3, gFld("audiere::RefImplementation< SoundEffect >", "", "classaudiere_1_1RefImplementation.html"))
             insDoc(aux4, gLnk("audiere::MultipleSoundEffect", "", "classaudiere_1_1MultipleSoundEffect.html"))
             insDoc(aux4, gLnk("audiere::SingleSoundEffect", "", "classaudiere_1_1SingleSoundEffect.html"))
       insDoc(aux1, gLnk("audiere::RefImplementation< Interface >", "", "classaudiere_1_1RefImplementation.html"))
       insDoc(aux1, gLnk("audiere::RefPtr< T >", "", "classaudiere_1_1RefPtr.html"))
       insDoc(aux1, gLnk("audiere::SizedBuffer", "", "classaudiere_1_1SizedBuffer.html"))
  aux2 = insFld(aux1, gFld("audiere::Synchronized", "", "classaudiere_1_1Synchronized.html"))
         insDoc(aux2, gLnk("audiere::DSAudioDevice", "", "classaudiere_1_1DSAudioDevice.html"))
         insDoc(aux2, gLnk("audiere::DSOutputStream", "", "classaudiere_1_1DSOutputStream.html"))
         insDoc(aux2, gLnk("audiere::MixerDevice", "", "classaudiere_1_1MixerDevice.html"))
         insDoc(aux2, gLnk("audiere::NullAudioDevice", "", "classaudiere_1_1NullAudioDevice.html"))
       insDoc(aux1, gLnk("audiere::ThreadInternal", "", "structaudiere_1_1ThreadInternal.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("audiere", "", "namespaceaudiere.html"))
       insDoc(aux1, gLnk("audiere::hidden", "", "namespaceaudiere_1_1hidden.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Namespace Members", "", "namespacemembers.html"))
     insDoc(foldersTree, gLnk("Graphical Class Hierarchy", "", "inherits.html"))
